site_name: Eric Riddoch
theme:
  name: material
  # custom_dir: overrides/
  features:
    - navigation.instant
    - navigation.tabs  
  palette:
    primary: blue

plugins:
  - search:
      lang:
        - en

extra_css:
  # paths are relative to the docs/ folder
  - stylesheets/extra.css

markdown_extensions:
  - meta # lets you add YAML --- key: value --- pairs to the top of md files
  # adds a paragraph symbol to headers to get links to them
  - toc:
      permalink: true
  - pymdownx.tabbed # tabs inline
  - pymdownx.superfences # use any plugins inside of tabs, admonitions, etc.
  - pymdownx.inlinehilite # highlight inline with `#!python print()`
  - pymdownx.highlight # syntax highlighting
  - pymdownx.mark # inline text highlighting with ==text==
  - pymdownx.keys # keyboard icons (https://facelessuser.github.io/pymdown-extensions/extensions/keys/#extendingmodifying-key-map-index)
  - admonition # !!! callouts like important, note, example, danger, warning
  - pymdownx.details # ??? and ???+ collapsible admonitions
  - attr_list # add html attrs and css classes with {: .some-css-class .some-other-css-class}
  # copy/pasting this makes emojis show up in black; add a custom style sheet to color/animate them
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
